### Model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct  # Change to your base model
trust_remote_code: true

### Method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z0_config.json

### Dataset
dataset: reviseqa
template: qwen
cutoff_len: 16384
overwrite_cache: true
preprocessing_num_workers: 32

### Output
output_dir: ./output/xtragpt-7b  # Change to your output path
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### Train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-6
num_train_epochs: 4.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### Logging
report_to: wandb
